import { Booking } from '@/lib/types/booking';

export const DEMO_BOOKINGS: Booking[] = [
  {
    id: 'demo-wedding-001',
    res_no: 'RES-2024-001',
    client_name: 'Sarah & Michael Chen',
    onsite_contact: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    phone: '(416) 555-0123',
    booking_date: '2024-01-15',
    event_date: '2024-06-15',
    event_day: 'Saturday',
    event_type: 'Wedding Reception',
    hall: 'Crystal Hall A',
    guests: 150,
    start_time: '18:00',
    end_time: '23:00',
    setup_time: '15:00',
    food_style: 'Plated Dinner',
    apps: 'Bruschetta, Caprese Skewers, Mini Quiche Assortment',
    mains: 'Herb-Crusted Salmon, Beef Tenderloin with Red Wine Reduction, Vegetarian Risotto',
    desserts: 'Wedding Cake (3-tier Vanilla & Chocolate), Chocolate Fountain with Fresh Fruit, Assorted French Pastries',
    dietary_notes: '10 vegetarian meals, 5 gluten-free, 3 nut allergies, 2 vegan',
    beverages: 'Open Bar (4 hours) - Beer, Wine, Spirits, Soft Drinks, Coffee & Tea Service',
    setup_details: 'Round tables of 10, white linens, gold chiavari chairs, dance floor 20x20ft, elevated head table for 12',
    additional_items: 'Custom floral centerpieces (roses & lilies), Photo booth area with props, Cake table with white backdrop, Gift table',
    av_requirements: 'Wireless lapel & handheld microphone system, Projector & 10ft screen for slideshow, DJ setup area with dedicated power circuit, Uplighting (purple & gold)',
    timeline: '3:00pm Venue setup begins | 5:00pm Vendor load-in | 6:00pm Cocktail hour (lobby) | 7:00pm Grand entrance | 7:15pm Dinner service | 8:45pm Speeches & toasts | 9:30pm First dance & dancing | 11:00pm Event end',
    billing_breakdown: 'Venue rental: $3,500 | Catering ($95/person x 150): $14,250 | Bar service (4hr): $2,800 | Linens & chairs: $950 | AV equipment package: $800 | Floral centerpieces: $1,200 | Service charge (18%): $4,230 | HST (13%): $3,575',
    total_amount: 31305.00,
    deposit_paid: 15652.50,
    balance_due: 15652.50,
    payment_status: 'deposit_paid',
    manager_name: 'Jennifer Martinez',
    onsite_mgr_name: 'Robert Kim',
    notes: 'Bride requested dim lighting during ceremony. Confirm cake delivery by 2pm. Photographer needs access at 3pm for pre-event shots.',
    status: 'confirmed',
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-03-10T14:15:00Z'
  },
  {
    id: 'demo-corporate-002',
    res_no: 'RES-2024-002',
    client_name: 'TechCorp Annual Gala',
    onsite_contact: 'Amanda Rodriguez',
    email: 'amanda.rodriguez@techcorp.com',
    phone: '(647) 555-0456',
    booking_date: '2024-02-20',
    event_date: '2024-05-19',
    event_day: 'Friday',
    event_type: 'Corporate Annual Dinner',
    hall: 'Crystal Hall B',
    guests: 200,
    start_time: '18:30',
    end_time: '22:30',
    setup_time: '14:00',
    food_style: 'Buffet Style',
    apps: 'Shrimp Cocktail Station, Charcuterie Display, Vegetable Crudités with Dips',
    mains: 'Carved Prime Rib, Grilled Chicken Breast with Herbs, Pan-Seared Sea Bass, Wild Mushroom Pasta (vegetarian)',
    desserts: 'Dessert Bar: Tiramisu, Cheesecake, Fruit Tarts, Chocolate Mousse',
    dietary_notes: '15 vegetarian, 8 vegan, 12 gluten-free, 4 halal',
    beverages: 'Beer & Wine Bar (3 hours), Signature Cocktails, Premium Coffee & Tea Station',
    setup_details: 'Theater-style seating for 200 (presentation), convert to dinner rounds of 10, stage with podium, corporate branding banners',
    additional_items: 'Registration desk with signage, Name badges, Corporate logo projection on walls, Award display table',
    av_requirements: 'Full PA system, 2 wireless mics + 1 lapel, 15ft projection screen, HD projector, Laptop connectivity (HDMI), Spotlights for stage, Video recording setup',
    timeline: '2:00pm Setup & AV check | 6:30pm Guest arrival & cocktails | 7:00pm Welcome speech | 7:15pm Dinner buffet opens | 8:30pm Awards ceremony | 9:30pm Networking & dessert | 10:30pm Event close',
    billing_breakdown: 'Venue rental (Friday premium): $4,200 | Buffet catering ($78/person x 200): $15,600 | Bar service (3hr): $3,400 | AV package (premium): $1,500 | Staging & branding: $800 | Service charge (18%): $4,590 | HST (13%): $3,962',
    total_amount: 34052.00,
    deposit_paid: 34052.00,
    balance_due: 0,
    payment_status: 'fully_paid',
    manager_name: 'David Park',
    onsite_mgr_name: 'Jennifer Martinez',
    notes: 'Client needs venue access early for branded setup. Confirm vegetarian count 48hrs before. CEO requires private green room.',
    status: 'confirmed',
    created_at: '2024-02-20T09:15:00Z',
    updated_at: '2024-04-01T11:30:00Z'
  },
  {
    id: 'demo-birthday-003',
    res_no: 'RES-2024-003',
    client_name: 'Priya Sharma 50th Birthday',
    onsite_contact: 'Raj Sharma',
    email: 'raj.sharma@email.com',
    phone: '(905) 555-0789',
    booking_date: '2024-03-01',
    event_date: '2024-07-20',
    event_day: 'Saturday',
    event_type: 'Birthday Celebration',
    hall: 'Garden Terrace',
    guests: 80,
    start_time: '19:00',
    end_time: '23:30',
    setup_time: '16:00',
    food_style: 'Family Style',
    apps: 'Samosas, Pakoras, Spring Rolls, Chicken Satay, Vegetable Platter',
    mains: 'Butter Chicken, Lamb Biryani, Tandoori Mixed Grill, Paneer Tikka Masala, Dal Makhani, Naan & Rice',
    desserts: 'Custom Birthday Cake (Mango & Cardamom), Gulab Jamun, Ras Malai, Ice Cream Station',
    dietary_notes: '20 strict vegetarian, 5 vegan, 3 dairy-free',
    beverages: 'Cash Bar - Beer, Wine, Soft Drinks, Mango Lassi, Masala Chai Service',
    setup_details: 'Round tables of 8, colorful linens (orange & gold), Bollywood-themed décor, Dance floor, DJ booth, Photo backdrop area',
    additional_items: 'Balloon arch entrance, Custom photo slideshow display, Gift table with decorative cloth, Henna artist station',
    av_requirements: 'DJ sound system with subwoofer, Wireless microphone, TV for photo slideshow, Colorful party lighting, Disco ball',
    timeline: '4:00pm Setup & decoration | 7:00pm Guest arrival | 7:30pm Cocktails & appetizers | 8:15pm Family speech | 8:30pm Dinner service | 9:30pm Cake cutting | 10:00pm Dancing & music | 11:30pm Event end',
    billing_breakdown: 'Venue rental (Saturday): $2,800 | Family-style catering ($65/person x 80): $5,200 | Cash bar setup: $300 | Décor package: $600 | AV & DJ package: $950 | Custom cake: $280 | Service charge (18%): $1,844 | HST (13%): $1,547',
    total_amount: 13521.00,
    deposit_paid: 4000.00,
    balance_due: 9521.00,
    payment_status: 'outstanding',
    manager_name: 'Sarah Thompson',
    onsite_mgr_name: 'David Park',
    notes: 'Family bringing their own decorations - confirm setup time. Vegetarian dishes to be clearly labeled. Birthday surprise at 9:30pm - coordinate with DJ.',
    status: 'tentative',
    created_at: '2024-03-01T13:45:00Z',
    updated_at: '2024-03-15T10:20:00Z'
  },
  {
    id: '21db2260-c6f2-4c10-9e46-4db28e6a61be',
    res_no: 'RES-2024-004',
    client_name: 'Mallika Sapkota',
    email: 'mallika.sapkota@email.com',
    phone: '(416) 555-0234',
    booking_date: '2024-04-01',
    event_date: '2026-05-19',
    event_day: 'Tuesday',
    event_type: 'Birthday Party',
    hall: 'Crystal Hall B',
    guests: 0,
    start_time: '18:00',
    end_time: '22:00',
    setup_time: '16:00',
    total_amount: 0,
    deposit_paid: 0,
    balance_due: 0,
    payment_status: 'outstanding',
    manager_name: 'Staff',
    status: 'tentative',
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-04-01T10:00:00Z'
  }
];
